# This workflow will install Python dependencies, generate the HTML pages and push them to a pre-defined repository (see below)

name: Update COVID-19 statistics

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '15 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the update tool
      run: |
        python3 sidep.py
    - name: Push to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo: dvanders/dvanders.github.io
        allow_empty_commit: false
        build_dir: build
        jekyll: false
